## Java Gradle CircleCI 2.0 configuration file
##
## Check https://circleci.com/docs/2.0/language-java/ for more details
##
#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/openjdk:11-jdk
#
#    working_directory: ~/repo
#
#    environment:
#      # Customize the JVM maximum heap limit
#      JVM_OPTS: -Xmx3200m
#      TERM: dumb
#
#    steps:
#      - checkout
#
#      - restore_cache:
#          keys:
#            - v1-dependencies-{{ checksum "build.gradle" }}
#            - v1-dependencies-
#
#      - run: gradle dependencies
#
#      - save_cache:
#          paths:
#            - ~/.gradle
#          key: v1-dependencies-{{ checksum "build.gradle" }}
#
#      - run:
#          name: Build Application
#          command: gradle build -x test -x check
#
#      - run:
#          name: Unit Test
#          command: gradle test
#
#      - store_artifacts:
#          path: build/reports/tests/test
#
#      - store_test_results:
#          path: build/test-results
#
#      - run:
#          name: Run PMD
#          command: gradle pmdMain pmdTest
#
#      - store_artifacts:
#          path: build/reports/pmd
#
#      - run:
#          name: Run SonarQube
#          command: gradle sonarqube --info
#          context: SonarCloud
#
