name: Java CI/CD with Gradle

on:
  push:
    branches:
      - main
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  Build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get short SHA
        id: s_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Notify slack starting build
        if: success()
        id: slack_build # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: 깃허브
          status: BUILD STARTING commit:${{ steps.s_sha.outputs.sha8 }}
          color: warning

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build_gradle
        run: ./gradlew build -x test -x check

      - name: Notify slack build success
        if: ${{ always() && steps.build_gradle.outcome == 'success' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_build.outputs.message_id }}
          channel: 깃허브
          status: BUILD SUCCESS commit:${{ steps.s_sha.outputs.sha8 }}
          color: good

      - name: Notify slack build failed
        if: ${{ always() && steps.build_gradle.outcome == 'failure' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_build.outputs.message_id }}
          channel: 깃허브
          status: BUILD FAILED commit:${{ steps.s_sha.outputs.sha8 }}
          color: danger

      - name: Make Batch File
        run: echo 'java -jar "%~dp0app.jar"' > build/libs/app.bat

      - name: Deploy Excutable JAR
        uses: actions/upload-artifact@v2
        with:
          name: ctip-app
          path: '**/build/libs/*.*'

      - name: Notify slack starting test
        if: success()
        id: slack_test # IMPORTANT: reference this step ID value in future Slack steps
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: 깃허브
          status: UNIT TEST STARTING commit:${{ steps.s_sha.outputs.sha8 }}
          color: warning

      - name: Unit Test
        id: unit_test
        run: ./gradlew test -x jacocoTestReport

      - name: Notify slack test success
        if: ${{ always() && steps.unit_test.outcome == 'success' }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_test.outputs.message_id }}
          channel: 깃허브
          status: UNIT TEST SUCCESS commit:${{ steps.s_sha.outputs.sha8 }}
          color: good

      - name: Notify slack test failed
        if: ${{always() && steps.unit_test.outcome == 'failure'}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          # Updates existing message from the first step
          message_id: ${{ steps.slack_test.outputs.message_id }}
          channel: 깃허브
          status: UNIT TEST FAILED commit:${{ steps.s_sha.outputs.sha8 }}
          color: danger

      - name: Publish Test Report Summary
        uses: mikepenz/action-junit-report@v2
        if: ${{ always() }}
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Test Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/tests/test
          destination_dir: junit

      - name: Test Code Coverage
        id: code_coverage
        run: ./gradlew jacocoTestReport jacocoTestCoverageVerification

      - name: Deploy Code Coverage Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/jacoco/test/html
          destination_dir: jacoco
      
      - name: Notify slack code coverage report done
        if: ${{ always()}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: 깃허브
          status: CODE COVERAGE REPORT DONE commit:${{ steps.s_sha.outputs.sha8 }}
          color: good


  Analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Set up JDK 11  # Minimum JDK version for SonarQube
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11

      - name: Run Checkstyle
        uses: nikitasavinov/checkstyle-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: 'github-pr-check'
          tool_name: 'Lint'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube --info

      - name: Run PMD
        run: ./gradlew pmdMain pmdTest

      - name: Deploy PMD Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/pmd
          destination_dir: pmd

      - name: Run Spotbugs
        run: ./gradlew spotbugsMain spotbugsTest --stacktrace

      - name: Deploy Spotbugs Report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/spotbugs
          destination_dir: spotbugs
          
      - name: Get short SHA
        id: s_sha
        run: echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        
      - name: Notify slack static analysis done
        if: ${{ always()}}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
        uses: voxmedia/github-action-slack-notify-build@v1
        with:
          channel: 깃허브
          status: STATIC ANALYSIS DONE commit:${{ steps.s_sha.outputs.sha8 }}
          color: good

 
